### ISSUE TITLE
Remove subl handler but launch via launchy? and with $EDITOR?

### ISSUE THREAD

**Issue by emilebosch** [charliesome/better_errors#300]
Hi all,
I've been struggling with getting better_erros to open in files in my sublime editor. I don't want to install a handler for just something trivial as this.

I've been using the `xray gem` (https://github.com/brentd/xray-rails) recently. Which shows partials on your page. When clicking it opens the partials up in the right editor. I was wondering if this is maybe a sensible default approach. 

Check the middleware here: https://github.com/brentd/xray-rails/blob/master/lib/xray/middleware.rb. If so i can do a PR. whachathink?

**Comment by rmm5t** [comment]
I might be misunderstanding your request here mainly because I don't understand where launchy (the gem?) plays a role here , but better_errors will already launch Sublime if you have your `EDITOR` environment variable set correctly. Of course this requires that your server is launched from an environment that already has this env variable set.
See https://github.com/charliesome/better_errors/blob/master/lib/better_errors.rb#L129-L133

```bash
export EDITOR=subl
```

Alternatively, you can override this in ruby by setting the `BetterErrors.editor` config variable.
See https://github.com/charliesome/better_errors/blob/master/lib/better_errors.rb#L15-L20

```ruby
BetterErrors.editor = :sublime
```

Aside, if nothing else is set, `:textmate` is currently the default. It might be worthwhile to consider making `:sublime` the new default. 
See https://github.com/charliesome/better_errors/blob/master/lib/better_errors.rb#L132

**Comment by emilebosch** [comment]
You re correct launchy doesn't play a role in it. (read the code wrong, apologies) But what xray does is basically execute a shell execute instead of a safari extension url. Therefore just basically works immediately out of the box without any addition url handler installs. 

```ruby
  # Request for opening a file path.
      if env['PATH_INFO'] == OPEN_PATH
        req, res = Rack::Request.new(env), Rack::Response.new
        out, err, status = Xray.open_file(req.GET['path'])
        if status.success?
          res.status = 200
        else
          res.write out
          res.status = 500
        end
        res.finish
```

Which works via a `POPEN`.

**Comment by rmm5t** [comment]
> Which works via a POPEN. Does this clarify my request?

Ah, I understand a little better now. Thanks for clarifying.

>  But what xray does is basically execute a shell execute instead of a safari extension url.

1. Officially, it's not a safari extension url. It's actually a registered URI scheme within OS X itself, and this is the recommended and arguably correct way to open files in specific applications. 
2. I would argue that Xray is doing this in a non-standard and hackish way. They require a completely separate configuration instead of relying on the standard `EDITOR` environment variable or standard URI schemes. Not to mention, if I'm understanding things correctly, they require middleware to respond to the click and execute a shell command on the server that just happens to launch your editor (this seems like spaghetti). They also have the extra liability of processing a xray-specific config file for the sole purpose of this editor configuration. 

Why do you feel the Xray mechanism is a better approach?

**Comment by emilebosch** [comment]
@rmm5t I understand your position that the URI handler is probably the cleanest approach. However i've never got it to a 'it-just-works-after-an install' state. I can select the application to open `subl` with once. But it will never remember my chosen application, and forces me to redo this all the time. Whereas XRAY just works after first install, even if its hackish. Stil right now i am puzzled how i can make my URI scheme permanently work, so i can just use better_errors without friction.

**Comment by rmm5t** [comment]
> But it will never remember my chosen application, and forces me to redo this all the time. 

Are you setting the `EDITOR=subl` environment variable or are you setting it using `BetterErrors.editor = :sublime`?  (The `EDITOR` approach is the recommended one)

If `EDITOR` env variable, make sure to put it in your shell profile script (e.g. `~/.bashrc`) so it runs everytime you start a new command shell.

```bash
export EDITOR=subl
```

For example, here's the line that configures my editor:
https://github.com/rmm5t/dotfiles/blob/master/bashrc#L155

>  Whereas XRAY just works after first install

That's probably _only_ because XRAY defaults to sublime (the editor you happen to use); whereas, better_errors defaults to textmate.

**Comment by emilebosch** [comment]
Well its not the EDITOR var thats the problem. its that safari just doesn't recognize the `subl://` handler. even after opening it with sublime. It doesn't remember, there is no way i can get safari to open a `subl://` scheme. Do i need to install something additionally?

**Comment by emilebosch** [comment]
So referring to: https://github.com/charliesome/better_errors/wiki, i need to install a sublime handler so i can just use the gem am i correct?

**Comment by rmm5t** [comment]
> i need to install a sublime handler so i can just use the gem am i correct? This seems to me a bit too much work just for getting a dev tool to work.

Yes. I didn't realize (and am surprised) that Sublime doesn't configure a URI scheme by default. 

> Using the even slightly so hackish way of using middleware to open files, has my preference over installing another piece of software which actually isn't installed that easily at all.

That's crazy talk. Registered URI schemes are the way every other editor handles this (and most applications in general for that matter). In fact (somewhat off topic) URI schemes were the only way iOS apps could even talk to one another before iOS 8. It sounds like Sublime is subpar here, but there's a good workaround.

**Comment by emilebosch** [comment]
IOS 8 is completely off topic here, we're not talking debugging a mobile device, or cross app communication. I am just looking for a frictionless way on how to open my files after better_errors captures them. 

But apparently you haven't got it SUBL handler itself running, or tried to get this baby running yourself. So you might not have felt the pain. Also this makes this discussion a bit awkward, I'm gonna branch off PR and solve it like xray. Feel free to merge or confine my PR to the burning dungeons of os land.

**Comment by rmm5t** [comment]
@emilebosch I think you're wasting your time and your breathe. Install the subl URI scheme and move on. It's the correct approach. XRAY's approach is a liability.

> I'm gonna branch off PR and solve it like xray. 

Fair enough. If you feel that strongly about this, go for it, but this perceived problem that you're facing looks like a big bikeshed with a ton of yak hair that you'll need to shave.
