### ISSUE TITLE
Clash with acts_as_taggable_on

### ISSUE THREAD

**Issue by rhulse** [charliesome/better_errors#324]
I use acts_as_taggable_on some of my models.

When I access a show page for the model and there is a simple ```NoMethodError``` then I see in the console that the system is loading all the tags for the taggable_type (i.e. my model) one by one, not just the one requested for the show page.

If I disable tagging on that model then the ```NoMethodError``` show up fine. 

Is this a config issue, or is ```better_errors``` going too far in getting context? 

Is there a way to get it to ignore certain things (tags) when there is an error?

**Comment by charliesome** [comment]
Are you able to get a backtrace for tag loads? I suspect that this is happening as part of better_errors variable inspection.

If it turns out that's the case, the best way to fix this would be to change the acts_as_taggable gem itself to not load tags as part of `inspect`.

If you're using a version of Rails earlier than 4.0 (I think), it might be Rails itself loading the tags on `inspect` rather than acts_as_taggable. In that case upgrading will fix it, or if upgrading is not feasible then I think it might be possible monkey patch that behaviour out.
