### ISSUE TITLE
Doesn't work in a nested Rack::Builder

### ISSUE THREAD

**Issue by RobinDaugherty** [charliesome/better_errors#397]
The following Rack app does not work with Better Errors:

```rb
app = Rack::Builder.new do
  use BetterErrors::Middleware
  run(proc { |env| raise "something" })
end

run app
```

The fix is to move the `use` call to the outermost scope.
But this should work, Better Errors should work anywhere in the middleware stack.

This was outlined in #298.

**Comment by VitorFalcao** [comment]
@RobinDaugherty I would like to start contributing to the project. Do you think this issue is appropriate for a new contributor? Could you give me some pointers? Thank you

**Comment by RobinDaugherty** [comment]
@VitorFalcao I think this issue might require knowledge of Rack middleware, which is why I haven't touched it yet. Please give it a try if you want!

**Comment by VitorFalcao** [comment]
@RobinDaugherty I've found the issue. The `@error_page` instance variable is lost when the `POST` call is made to retrieve the information required to create the REPL. This happens because a new instance of `BetterErros::Middleware` is created each time a request reaches the application. So, in details:
This is the Rack app you gave as an example:
```ruby
app = Rack::Builder.new do
  use BetterErrors::Middleware
  run(proc { |env| raise "something" })
end
```
This line `use BetterErros::Middleware` calls the method below:
https://github.com/rack/rack/blob/6b942ff543416e0c82196f0790d4915c7eead4cb/lib/rack/builder.rb#L81-L87
And, as you can see, on line 86 a new instance of the `middleware` is created each time this method is executed. In this case, `middleware == BetterErrors::Middleware`, therefore the information that was saved into `@error_page` is lost. So when the `POST` request comes in, the code in line # 133 below is executed.
https://github.com/charliesome/better_errors/blob/613caa840f3cc9182fdfdcabadbd22e1d3d4fdcb/lib/better_errors/middleware.rb#L132-L139
I don't see another way around this if not to put `use BetterErrors::Middleware` outside the `Rack::Builder` block (it can be before or after the block).

**Comment by VitorFalcao** [comment]
@RobinDaugherty I was thinking that the solution to that might be to use a Singleton? What's your thought on that?

**Comment by RobinDaugherty** [comment]
> Instead of first returning the frames and then making a post request to retrieve the information required to create the REPL, couldn't it just return everything together?
The biggest barrier to this would be serializing all data for every stack frame. As it is, we have to eliminate variables that are too large to serialize, but those variables would be needed when the REPL is being used. So I have a strong feeling that's a non-starter.

A singleton might work, but that would probably cause problems for multiprocess servers. It would also need to be threadsafe. On the other hand, the readme already says not to use multiple processes, so it may not cause new problems.

Is it possible to create an instance of `BetterErrors::Middleware` and then pass that to the `use` method instead of passing the class itself?

**Comment by VitorFalcao** [comment]
> The biggest barrier to this would be serializing all data for every stack frame. As it is, we have to eliminate variables that are too large to serialize, but those variables would be needed when the REPL is being used. So I have a strong feeling that's a non-starter.

Thanks for pointing this out.

> Is it possible to create an instance of BetterErrors::Middleware and then pass that to the use method instead of passing the class itself?

I am afraid no. This is how the method `use` of `Rack::Builder` works:

```ruby
def use(middleware, *args, &block)
      if @map
        mapping, @map = @map, nil
        @use << proc { |app| generate_map app, mapping }
      end
      @use << proc { |app| middleware.new(app, *args, &block) }
end
```
So it always creates a new instance.

**Comment by RobinDaugherty** [comment]
I'm willing to leave it at "BetterErrors must be used in the global context as Rack middleware, and cannot be `use`d inside of a `Rack::Builder`.

Thanks for your help on this @VitorFalcao!

**Comment by evanleck** [comment]
FWIW you can use BetterErrors with `Rack::Builder` by calling `#to_app` on your `Rack::Builder.new` instance.

---

This may be particular to my setup, but I have approximately this in `config/application.rb`:

```ruby
Application = Rack::Builder.new do
  # Set it up with BetterErrors middleware.
end
```

And this in `config.ru`:

```ruby
require 'config/application'

run Application
```

In that setup, I consistently get errors about the application being restarted. However, adding `#to_app` to `config/application.rb` gets everything working fine.

```ruby
Application = Rack::Builder.new do
  # Set it up with BetterErrors middleware.
end.to_app
```

[`Rack::Builder#to_app`](https://github.com/rack/rack/blob/2a5f80d189c77817feb568ceaa841df2b9fb5921/lib/rack/builder.rb#L150-L157) gets called automatically by [`Rack::Builder#call`](https://github.com/rack/rack/blob/2a5f80d189c77817feb568ceaa841df2b9fb5921/lib/rack/builder.rb#L159-L161), but by assigning the result of `#to_app` to `Application` we skip calling `#to_app` every time, thereby not reinitializing the Rack application stack each time and making BetterErrors happy.

Not sure if that's the best explanation, but I thought I'd share 😄
